---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: dbservers
  remote_user: kaixi
  become: yes
  become_method: sudo
  roles:
    - dbservers

- hosts: webservers
  remote_user: kaixi
  become: yes
  become_method: sudo
  roles:
    - webservers
